// Replace the embroidery placement previews on each Black Vault Shopify draft
// with REAL product mockups generated by Printful's mockup generator API
// (technique=EMBROIDERY, placement=embroidery_chest_left, Old Gold thread).
//
// These are the photos that show the actual blank garment with the BV monogram
// rendered as embroidery — what a customer actually wants to see on a listing.
//
// Run with:
//   node --env-file=.env.local --require ./scripts/server-only-stub.cjs --import tsx scripts/blackvault-generate-mockups.ts

import fs from "node:fs";
import path from "node:path";
import { resolveShopifyCredentials } from "@/lib/shopify-credentials";

const BRAND = "black-vault-apparel";
const BRAND_DIR = path.join(process.cwd(), ".openclaw", "brand");
// Monogram-only crop of BV Transpo.png. We dropped the "BLACK VAULT APPAREL"
// wordmark from the embroidery file because at chest-emblem size (~2.5in) the
// wordmark text rendered as illegible thread garbage and Printful was showing
// the design's bounding box as a faint square. See scripts/blackvault-extract-monogram.ts
// (or just use sharp on .openclaw/brand/BV Transpo.png).
const LOGO_PATH = path.join(BRAND_DIR, "BV Monogram.png");
const RESULTS_PATH = path.join(BRAND_DIR, "launch-collection-results.json");

const THREAD_COLOR_OLD_GOLD = "#A67843";
const PF_BASE = "https://api.printful.com";

// Map results.json slug → base variant id (need product_id) AND shopify image cleanup
const COLLECTION = [
  { slug: "the-monogram-tee", baseVariantId: 12757 },
  { slug: "the-vault-tee", baseVariantId: 15115 },
  { slug: "the-heavyweight-hoodie", baseVariantId: 21153 },
  { slug: "the-crewneck", baseVariantId: 22127 },
  { slug: "the-long-sleeve", baseVariantId: 19214 }
];

type Result = {
  slug: string;
  name: string;
  shopifyProductId?: number;
  printfulSyncProductId?: number;
  status: string;
};

function ensurePrintful() {
  const token = process.env.PRINTFUL_API_KEY?.trim();
  const storeId = process.env.PRINTFUL_STORE_ID?.trim();
  if (!token) throw new Error("Missing PRINTFUL_API_KEY");
  if (!storeId) throw new Error("Missing PRINTFUL_STORE_ID");
  return { token, storeId };
}

async function pfFetch(method: "GET" | "POST", urlPath: string, body?: unknown) {
  const { token, storeId } = ensurePrintful();
  const r = await fetch(`${PF_BASE}${urlPath}`, {
    method,
    headers: {
      Authorization: `Bearer ${token}`,
      "X-PF-Store-Id": storeId,
      ...(body ? { "Content-Type": "application/json" } : {})
    },
    body: body ? JSON.stringify(body) : undefined
  });
  const text = await r.text();
  if (!r.ok) throw new Error(`Printful ${method} ${urlPath} (${r.status}): ${text}`);
  return text ? JSON.parse(text) : {};
}

// --- Shopify ---------------------------------------------------------------

type ShopifyCreds = { storeDomain: string; apiVersion: string; token: string };

async function shopifyRest<T>(creds: ShopifyCreds, endpoint: string, init: RequestInit) {
  const r = await fetch(`https://${creds.storeDomain}/admin/api/${creds.apiVersion}${endpoint}`, {
    ...init,
    headers: {
      "X-Shopify-Access-Token": creds.token,
      "Content-Type": "application/json",
      ...(init.headers ?? {})
    }
  });
  const text = await r.text();
  if (!r.ok) throw new Error(`Shopify ${init.method ?? "GET"} ${endpoint} (${r.status}): ${text}`);
  return text ? (JSON.parse(text) as T) : ({} as T);
}

async function shopifyGraphQL<T>(creds: ShopifyCreds, query: string, variables: Record<string, unknown>) {
  const r = await fetch(`https://${creds.storeDomain}/admin/api/${creds.apiVersion}/graphql.json`, {
    method: "POST",
    headers: { "X-Shopify-Access-Token": creds.token, "Content-Type": "application/json" },
    body: JSON.stringify({ query, variables })
  });
  const text = await r.text();
  const parsed: { data?: T; errors?: unknown } = text ? JSON.parse(text) : {};
  if (!r.ok || (Array.isArray(parsed.errors) && parsed.errors.length > 0)) {
    throw new Error(`Shopify GraphQL (${r.status}): ${text}`);
  }
  return parsed.data as T;
}

async function uploadLogoOnce(creds: ShopifyCreds): Promise<string> {
  const buffer = fs.readFileSync(LOGO_PATH);
  const filename = "blackvault-monogram-mockup.png";
  const staged = await shopifyGraphQL<{
    stagedUploadsCreate: { stagedTargets: Array<{ url: string; resourceUrl: string; parameters: Array<{ name: string; value: string }> }>; userErrors: Array<{ message: string }> };
  }>(creds, `mutation($input: [StagedUploadInput!]!) {
    stagedUploadsCreate(input: $input) { stagedTargets { url resourceUrl parameters { name value } } userErrors { message } }
  }`, { input: [{ filename, mimeType: "image/png", httpMethod: "POST", resource: "FILE" }] });
  const target = staged.stagedUploadsCreate.stagedTargets[0];
  if (!target) throw new Error("staged upload returned no target");
  const form = new FormData();
  for (const p of target.parameters) form.append(p.name, p.value);
  form.append("file", new Blob([buffer], { type: "image/png" }), filename);
  const upload = await fetch(target.url, { method: "POST", body: form });
  if (!upload.ok) throw new Error(`staged POST ${upload.status}`);
  const fileData = await shopifyGraphQL<{
    fileCreate: { files: Array<{ id?: string; image?: { url?: string }; url?: string }>; userErrors: Array<{ message: string }> };
  }>(creds, `mutation($files: [FileCreateInput!]!) {
    fileCreate(files: $files) { files { ... on MediaImage { id image { url } } ... on GenericFile { id url } } userErrors { message } }
  }`, { files: [{ originalSource: target.resourceUrl, contentType: "IMAGE", filename }] });
  const file = fileData.fileCreate.files[0];
  if (!file?.id) throw new Error("fileCreate returned no id");
  let url = file.url ?? file.image?.url ?? "";
  for (let i = 0; i < 20 && !url; i += 1) {
    await new Promise((r) => setTimeout(r, 750 + i * 250));
    try {
      const polled = await shopifyGraphQL<{ node: { url?: string; image?: { url?: string } } | null }>(creds,
        `query($id: ID!) { node(id: $id) { ... on MediaImage { id image { url } } ... on GenericFile { id url } } }`,
        { id: file.id });
      url = polled.node?.url ?? polled.node?.image?.url ?? "";
    } catch {}
  }
  if (!url) throw new Error("logo never returned URL");
  return url;
}

async function listShopifyImages(creds: ShopifyCreds, productId: number): Promise<Array<{ id: number }>> {
  const data = await shopifyRest<{ images: Array<{ id: number }> }>(creds, `/products/${productId}/images.json`, { method: "GET" });
  return data.images ?? [];
}

async function deleteShopifyImage(creds: ShopifyCreds, productId: number, imageId: number) {
  await shopifyRest(creds, `/products/${productId}/images/${imageId}.json`, { method: "DELETE" });
}

async function attachShopifyImage(creds: ShopifyCreds, productId: number, src: string, alt: string) {
  await shopifyRest(creds, `/products/${productId}/images.json`, {
    method: "POST",
    body: JSON.stringify({ image: { src, alt } })
  });
}

// --- Printful mockup generator ---------------------------------------------

async function getProductMeta(variantId: number) {
  const data = await pfFetch("GET", `/products/variant/${variantId}`);
  const productId = data.result?.variant?.product_id as number;
  // Pull all Black size variants so the mockup task covers the size range
  const product = await pfFetch("GET", `/products/${productId}`);
  const order = ["S", "M", "L", "XL", "2XL"];
  const blackVariants: Array<{ id: number; size: string; color: string }> = (product.result?.variants ?? [])
    .filter((v: { color?: string; size?: string }) => /black/i.test(v.color ?? "") && order.includes(v.size ?? ""))
    .sort((a: { size: string }, b: { size: string }) => order.indexOf(a.size) - order.indexOf(b.size));
  return { productId, variantIds: blackVariants.map((v) => v.id) };
}

async function createEmbroideryMockupTask(productId: number, variantIds: number[], imageUrl: string): Promise<string> {
  // Embroidery chest area for these blanks is 1200x1200 @ 300dpi (4"x4").
  // Standard left-chest emblem is ~2.5" wide → 750px centered with margin.
  // Verified via /mockup-generator/printfiles?technique=EMBROIDERY.
  // Note: top-level `options` here is a VARIANT FILTER, not embroidery config —
  // setting `thread_colors_chest_left` would exclude all variants. The mockup
  // visual just renders the design; thread color matters for production only
  // (already set on the sync product variant options).
  const body = {
    variant_ids: variantIds,
    format: "jpg",
    technique: "EMBROIDERY",
    files: [
      {
        placement: "embroidery_chest_left",
        image_url: imageUrl,
        position: {
          area_width: 1200,
          area_height: 1200,
          width: 650,
          height: 650,
          top: 275,
          left: 175
        }
      }
    ]
  };
  const data = await pfFetch("POST", `/mockup-generator/create-task/${productId}`, body);
  const taskKey = data.result?.task_key as string | undefined;
  if (!taskKey) throw new Error("create-task returned no task_key: " + JSON.stringify(data));
  return taskKey;
}

async function pollMockupTask(taskKey: string, maxAttempts = 30, intervalMs = 4000): Promise<string[]> {
  for (let i = 0; i < maxAttempts; i += 1) {
    await new Promise((r) => setTimeout(r, intervalMs));
    const data = await pfFetch("GET", `/mockup-generator/task?task_key=${encodeURIComponent(taskKey)}`);
    const status = data.result?.status as string | undefined;
    if (status === "completed") {
      const mockups = (data.result?.mockups ?? []) as Array<{ mockup_url?: string; extra?: Array<{ url?: string }> }>;
      const urls = new Set<string>();
      mockups.forEach((m) => {
        if (m.mockup_url) urls.add(m.mockup_url);
        (m.extra ?? []).forEach((e) => e.url && urls.add(e.url));
      });
      return [...urls];
    }
    if (status === "failed") throw new Error("Mockup task failed: " + JSON.stringify(data.result));
  }
  throw new Error(`Mockup task ${taskKey} timed out`);
}

// --- Main ------------------------------------------------------------------

async function main() {
  ensurePrintful();
  const shopifyCreds = resolveShopifyCredentials(BRAND);
  const results: Result[] = JSON.parse(fs.readFileSync(RESULTS_PATH, "utf8"));
  console.log(`[init] re-uploading BV monogram for mockup generator…`);
  const designUrl = await uploadLogoOnce(shopifyCreds);
  console.log(`[init] design URL: ${designUrl}\n`);

  for (let idx = 0; idx < COLLECTION.length; idx += 1) {
    const cfg = COLLECTION[idx];
    const item = results.find((r) => r.slug === cfg.slug && r.shopifyProductId);
    if (!item) {
      console.log(`[${cfg.slug}] no Shopify result — skipping`);
      continue;
    }
    if (idx > 0) {
      // Printful's mockup generator rate-limits aggressively (~60s between
      // create-task calls). Sleep before each subsequent product.
      console.log(`\n[rate-limit] sleeping 65s before next mockup task…`);
      await new Promise((r) => setTimeout(r, 65000));
    }
    console.log(`\n[${cfg.slug}] generating mockups…`);
    try {
      const meta = await getProductMeta(cfg.baseVariantId);
      console.log(`  product_id=${meta.productId} variants=${meta.variantIds.join(",")}`);
      const taskKey = await createEmbroideryMockupTask(meta.productId, meta.variantIds, designUrl);
      console.log(`  task_key=${taskKey} polling…`);
      const urls = await pollMockupTask(taskKey);
      console.log(`  ${urls.length} mockup URLs returned`);

      // Wipe existing images and attach the new mockups (cap at 5 to keep the listing clean)
      const existing = await listShopifyImages(shopifyCreds, item.shopifyProductId!);
      for (const img of existing) {
        await deleteShopifyImage(shopifyCreds, item.shopifyProductId!, img.id);
      }
      console.log(`  wiped ${existing.length} existing images`);
      const toAttach = urls.slice(0, 5);
      for (const url of toAttach) {
        await attachShopifyImage(shopifyCreds, item.shopifyProductId!, url, item.name);
      }
      console.log(`  ✓ attached ${toAttach.length} new mockups`);
    } catch (e) {
      console.warn(`[${cfg.slug}] failed: ${e instanceof Error ? e.message : e}`);
    }
  }

  console.log("\nDone.");
}

main().catch((e) => { console.error(e); process.exit(1); });
